version: "3.9"
services:
  ejercicio-2:
    image: "postgres:14.5-alpine"
    hostname: molinetes-db
    container_name: molinetes-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./molinetes-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - molinetes-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  populate:
    build: ./ejercicio-4/
    image: molinetes-populate
    container_name: molinetes-populate
    networks:
      - molinetes-network
    depends_on:
      ejercicio-2:
        condition: service_healthy
  app:
    build: ./ejercicio-5/
    image: molinetes-app
    container_name: molinetes-app
    ports:
      - 5000:5000
    networks:
      - molinetes-network
    depends_on:
      populate:
        condition: service_completed_successfully

networks:
  molinetes-network:
    name: molinetes-network